# Generated by Django 3.0.5 on 2020-12-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('policytype', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=15)),
                ('sum_insured', models.IntegerField()),
            ],
        ),
    ]
