# Generated by Django 3.0.5 on 2020-12-11 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Policy',
        ),
    ]
